In [1]:
using Sub2Index

In [2]:
@macroexpand @_ Fₙ = Fₙ₋₁ + Fₙ₋₂

:(F[n] = F[n - 1] + F[n - 2])

In [3]:
F = ones(Int, 10)

@_ for n = 3:10
    Fₙ = Fₙ₋₁ + Fₙ₋₂
end

F

10-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13
 21
 34
 55

In [4]:
@macroexpand @_ Π₍ᵢ₎₍ⱼ₎ = Π₍ᵢ₋₁₎₍ⱼ₋₁₎ + Π₍ᵢ₋₁₎₍ⱼ₎

:(Π[i, j] = Π[i - 1, j - 1] + Π[i - 1, j])

In [5]:
Π = zeros(Int, (10, 10))

@_ for i = 1:10 Π₍ᵢ₎₍₁₎ = Π₍ᵢ₎₍ᵢ₎ = 1 end
@_ for i = 3:10, j = 2:i-1
    Π₍ᵢ₎₍ⱼ₎ = Π₍ᵢ₋₁₎₍ⱼ₋₁₎ + Π₍ᵢ₋₁₎₍ⱼ₎
end

Π

10×10 Array{Int64,2}:
 1  0   0   0    0    0   0   0  0  0
 1  1   0   0    0    0   0   0  0  0
 1  2   1   0    0    0   0   0  0  0
 1  3   3   1    0    0   0   0  0  0
 1  4   6   4    1    0   0   0  0  0
 1  5  10  10    5    1   0   0  0  0
 1  6  15  20   15    6   1   0  0  0
 1  7  21  35   35   21   7   1  0  0
 1  8  28  56   70   56  28   8  1  0
 1  9  36  84  126  126  84  36  9  1

In [6]:
@macroexpand @_ Gₙ = Gₙ₋₁Gₙ₋₂

:(G[n] = G[n - 1] * G[n - 2])

In [7]:
G = zeros(Int128, 10)
@_ begin
    G₁ = 1
    G₂ = 2
    for n = 3:10
        Gₙ = Gₙ₋₁Gₙ₋₂  # equivalent to `G[n] = G[n - 1] * G[n - 2]`
    end
end
G

10-element Array{Int128,1}:
           1
           2
           2
           4
           8
          32
         256
        8192
     2097152
 17179869184